### ISSUE TITLE
None values in series are ignored

### ISSUE THREAD

**Issue by LukaszWakeapp** [highcharts-for-python/highcharts-core#168]
I have 2 series:
`data_set = [53,12,25,36,43,12,21]`
`data_set_2 = [55,None,None,None,None,None,22]`

expected behaviour (using code from chart.to_js_literal()):
![obraz](https://github.com/highcharts-for-python/highcharts-core/assets/101632273/f695115e-3b7d-4236-bbe6-e25acbfa0271)

after downloading (not displaying in python just downloading):
![chart-backlinks](https://github.com/highcharts-for-python/highcharts-core/assets/101632273/f3d63e0a-ff6f-475a-a582-88ef238d6146)

Why after downloading nulls are ignored?

`chart.download_chart(
    format = 'png',
    filename = 'images/chart.png'
)`

**Comment by hcpchris** [comment]
@LukaszWakeapp : FYI - thanks for bringing this bug to our attention. It should be resolved in v.1.8.0 which was just released.
