### ISSUE TITLE
JS literal containing `+` for string concatenation breaks `from_js_literal()`

### ISSUE THREAD

**Issue by JulienBacquart** [highcharts-for-python/highcharts-core#185]
Trying to reproduce [Stacked percentage column](https://www.highcharts.com/demo/highcharts/column-stacked-percent)

```python
options_as_str = """{
    chart: {
        type: 'column'
    },
    title: {
        text: 'Domestic passenger transport by mode of transport, Norway',
        align: 'left'
    },
    subtitle: {
        text: 'Source: <a href="https://www.ssb.no/transport-og-reiseliv/landtransport/statistikk/innenlandsk-transport">SSB</a>',
        align: 'left'
    },
    xAxis: {
        categories: ['2019', '2020', '2021']
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Percent'
        }
    },
    tooltip: {
        pointFormat: 
            '<span style="color:{series.color}">{series.name}</span>' +
            ': <b>{point.y}</b> ({point.percentage:.0f}%)<br/>',
            // '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>',
        shared: true
    },
    plotOptions: {
        column: {
            stacking: 'percent',
            dataLabels: {
                enabled: true,
                format: '{point.percentage:.0f}%'
            }
        }
    },
    series: [{
        name: 'Road',
        data: [434, 290, 307]
    }, {
        name: 'Rail',
        data: [272, 153, 156]
    }, {
        name: 'Air',
        data: [13, 7, 8]
    }, {
        name: 'Sea',
        data: [55, 35, 41]
    }]
}"""

options = HighchartsOptions.from_js_literal(options_as_str)
bar_chart = Chart.from_options(options)
bar_chart.display()
```

It seems the `+` is often used in the JS examples to break lines too long, but it breaks the `from_js_literal()` function.

If we look at the [parse tree generated by Esprima](https://esprima.org/demo/parse.html?code=var%20dict%20%3D%20options_as_str%20%3D%20%7B%0A%20%20%20%20chart%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20'column'%0A%20%20%20%20%7D%2C%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20%20%20text%3A%20'Domestic%20passenger%20transport%20by%20mode%20of%20transport%2C%20Norway'%2C%0A%20%20%20%20%20%20%20%20align%3A%20'left'%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20text%3A%20'Source%3A%20%3Ca%20href%3D%22https%3A%2F%2Fwww.ssb.no%2Ftransport-og-reiseliv%2Flandtransport%2Fstatistikk%2Finnenlandsk-transport%22%3ESSB%3C%2Fa%3E'%2C%0A%20%20%20%20%20%20%20%20align%3A%20'left'%0A%20%20%20%20%7D%2C%0A%20%20%20%20xAxis%3A%20%7B%0A%20%20%20%20%20%20%20%20categories%3A%20%5B'2019'%2C%20'2020'%2C%20'2021'%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20yAxis%3A%20%7B%0A%20%20%20%20%20%20%20%20min%3A%200%2C%0A%20%20%20%20%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20'Percent'%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20tooltip%3A%20%7B%0A%20%20%20%20%20%20%20%20pointFormat%3A%20%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3Cspan%20style%3D%22color%3A%7Bseries.color%7D%22%3E%7Bseries.name%7D%3C%2Fspan%3E'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20'%3A%20%3Cb%3E%7Bpoint.y%7D%3C%2Fb%3E%20(%7Bpoint.percentage%3A.0f%7D%25)%3Cbr%2F%3E'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20'%3Cspan%20style%3D%22color%3A%7Bseries.color%7D%22%3E%7Bseries.name%7D%3C%2Fspan%3E%3A%20%3Cb%3E%7Bpoint.y%7D%3C%2Fb%3E%20(%7Bpoint.percentage%3A.0f%7D%25)%3Cbr%2F%3E'%2C%0A%20%20%20%20%20%20%20%20shared%3A%20true%0A%20%20%20%20%7D%2C%0A%20%20%20%20plotOptions%3A%20%7B%0A%20%20%20%20%20%20%20%20column%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20stacking%3A%20'percent'%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20dataLabels%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20enabled%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20format%3A%20'%7Bpoint.percentage%3A.0f%7D%25'%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20series%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20name%3A%20'Road'%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B434%2C%20290%2C%20307%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20'Rail'%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B272%2C%20153%2C%20156%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20'Air'%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B13%2C%207%2C%208%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20'Sea'%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B55%2C%2035%2C%2041%5D%0A%20%20%20%20%7D%5D%0A%7D%3B)

```
-
#6
type: Property
-
key
type: Identifier
name: tooltip
computed: false
-
value
    type: ObjectExpression
    -
    properties
    -
    #1
    type: Property
    -
    key
    type: Identifier
    name: pointFormat
    computed: false
    -
    value
        type: BinaryExpression
        operator: +
        -
        left
        type: Literal
        value: <span style="color:{series.color}">{series.name}</span>
        raw: '<span style="color:{series.color}">{series.name}</span>'
        -
        right
        type: Literal
        value: : <b>{point.y}</b> ({point.percentage:.0f}%)<br/>
        raw: ': <b>{point.y}</b> ({point.percentage:.0f}%)<br/>'
        kind: init
        method: false
        shorthand: false
```

We can see we generate a `BinaryExpression` which is not a value type covered by [js_literal_functions()](https://github.com/highcharts-for-python/highcharts-core/blob/master/highcharts_core/js_literal_functions.py#L507).

A possible solution could look something like that:

```Python
    ...
    elif property_definition.value.type == 'BinaryExpression':
        property_value = property_definition.value
        operator = property_value.operator
        left, right = property_value.left, property_value.right
        left_type, right_type = left.type, right.type
        
        if (left_type not in ['Literal']) or (right_type not in ['Literal']):
            raise errors.HighchartsParseError(f'unable to find two Literal values within'
                                              f'a Binary expression. Found: '
                                              f'{left_type, right_type}')

        left_value, right_value = left.value, right.value
        
        if checkers.is_string(left_value) and checkers.is_string(right_value):
            if operator == '+':
                return left_value + right_value
            elif ...:
                 ...
        else:
            ...
```

If you want to open the can of worm of all valid combinaisons of types and binary operations, so we could write thing like `min : 0.8 * 100,` or `text: 'Domestic passenger for the year ' + 2012,`, is for you to decide.

**Comment by hcpchris** [comment]
Thanks, @JulienBacquart : This is a great catch. And I definitely appreciate the potential solution you propose. Let me give this one a little more thought - on the one hand, you're absolutely right that supporting the different type/binary operations is a can of worms...on the other hand, if we want to keep the promise of full support we probably should. Hmm. It's a bit of a conundrum. Let me give it a bit of thought. 

In either case, supporting the `+` should be something that gets tackled in the next release.

**Comment by JulienBacquart** [comment]
Implementing completely [Binary Expression](https://docs.esprima.org/en/latest/syntax-tree-format.html#binary-expression) would mean implementing all the following operators and all the possible combinaison of types possibles:
```
operator: 'instanceof' | 'in' | '+' | '-' | '*' | '/' | '%' | '**' |
        '|' | '^' | '&' | '==' | '!=' | '===' | '!==' |
        '<' | '>' | '<=' | '<<' | '>>' | '>>>';
```
At this point you are re-implementing a whole javascript interpreter.
And I don't know much JS, but even I know that you can write some pretty cursed expression in JS because of the casting never failing:
```Javascript
"b" + "a" + +"a" + "a"; // -> 'baNaNa' 
```
