### ISSUE TITLE
Specify the minimum python version supported in README

### ISSUE THREAD

**Issue by benjcabalona1029** [highcharts-for-python/highcharts-core#37]
From my testing, i'm only able to install it using python 3.10+. It would be nice if that is mentioned in the docs/ readme.

**Comment by hcpchris** [comment]
Thanks - it’s called out in the [primary documentation](https://core-docs.highchartspython.com/en/latest/) and on [PyPi](https://pypi.org/project/highcharts-core/#data) in the Meta section, but not in the README, which is definitely an oversight that should be fixed (and will be in the next release). Thanks for pointing it out!
