### ISSUE TITLE
Example: adding multiple series from a pandas dataframe

### ISSUE THREAD

**Issue by c-jamie** [highcharts-for-python/highcharts-core#59]
Hi there,

Is there an example of adding multiple `LineSeries` from a single dataframe?

**Comment by hcpchris** [comment]
Hi @c-jamie - unfortunately, we don't yet have a demo of how to do this in our set of Highcharts for Python demos, but the process should be fairly straightforward. 

In general, this assumes that you have your dataframe oriented in *columns* (which is an assumption already present for the ``.from_pandas()`` method). With that assumption, the basic process is the same (pseudocode below, but it should be fairly clear):

``` python
from highcharts_core.chart import Chart
from highcharts_core.options.series.area import LineSeries

# Assuming this is the Dataframe:

df = pandas.DataFrame(...)

# First, you create your Chart instance. 
# You can just as easily do this using Chart.from_pandas() 
# to populate it with a single series from your DataFrame if you want, 
# but the point is that you need your Chart instance before you add 
# additional series.

my_chart = Chart()

# Next, create the set of property_map instructions for each of your series.
# The assumption here is that if you have 3 different series, that the
# property_map for series1 will be different (the y-value will probably 
# point to a different column) from the property_map for series2, etc.

series1_property_map = { ... }
series2_property_map = { ... }
series3_property_map = { ... }

# Next, you create your set of LineSeries instances using .from_pandas()
# The expectation here is that series1 has a different value of 

series1 = LineSeries.from_pandas(df, property_map = series1_property_map)
series2 = LineSeries.from_pandas(df, property_map = series2_property_map)
series3 = LineSeries.from_pandas(df, property_map = series3_property_map)

# Then you add those series to your Chart instance.

my_chart.add_series(series1, series2, series3)
```

And that's it. Your chart should now have 3 series, and you can display it using ``.display()`` or render it to web using ``.to_js_literal()``, etc.

While it isn't using the ``LineSeries.from_pandas()`` method to instantiate the line series, you can see the same basic principle at play in the [Highcharts for Python Demo](https://github.com/highcharts-for-python/highcharts-for-python-demos) found at: ``highcharts-core/line-charts/basic-line.ipynb``.

Really, the only difference is how you create your line series instance, and you can just use ``from_pandas()`` as outlined above. Hope this helps, and if you have any other questions please let us know!
