### ISSUE TITLE
BUG: Annotations.draggable property should accept an empty string as a valid value

### ISSUE THREAD

**Issue by bgreenawald-vt** [highcharts-for-python/highcharts-core#71]
**Describe the bug**
The `Chart.to_dict()` method ignores keys which have a value of an empty string, but a value of empty string means something for the `Annotations.draggable` parameter (https://api.highcharts.com/highcharts/annotations.draggable) meaning that, in practice, you can't disable draggable annotations using that parameter.

**To Reproduce**
1. Create a Chart that has annotations, including the `draggable` parameter set to a value of `""`
```python
chart_options = { 
        "title": {"text": "Chart title"},
        "annotations": [
            {
                "labels": annotations,  # List of annotations
                "draggable": "",
                "labelOptions": {
                    "backgroundColor": "rgba(252, 255, 255, 0.0)",
                    "borderColor": "rgba(252, 255, 255, 0.0)",
                    "allowOverlap": True,
                    "y": -2,
                    "overflow": "justify"
                },
            }
        ]
    }

chart = Chart.from_options(chart_options)
```
2. Export the Chart to a dictionary using the `to_dict` method and inspect the `userOptions` in the result. Note in the picture below that all parameters have been preserved _except_ `draggable`:
```python
chart.to_dict()["userOptions"]
```
![image](https://github.com/highcharts-for-python/highcharts-core/assets/122644400/652b62e2-8769-46cc-8893-2c12daa0828b)

**Expected behavior**
The `draggable` parameter should be preserved, even when the value is an empty string.

**Your Environment:**
 - OS: Windows 11
 - Python Version: 3.11
 - Highcharts JavaScript Version: highcharts-core==1.2.4

**Additional context**
Tracing the issue with the debugger, I isolated the following line as the problem. `metaclasses.py -> lines 253, 254` 
```python
elif value in [0, 0., False]:
    as_dict[key] = value
```
Locally, I was able to correct the issue by adding an empty string in the list of permitted values, though I don't know what other affects this might have.

**Comment by hcpchris** [comment]
Thanks, @bgreenawald-vt ! This is a good catch, and definitely looks like a bug. I'll take a closer look and patch it in the next release (v.1.2.6 - hopefully later today).
