### ISSUE TITLE
xAxis.labels.style isn't applying styles correctly

### ISSUE THREAD

**Issue by ndrwkim** [highcharts-for-python/highcharts-core#82]
I am setting [xAxis.labels.style](https://api.highcharts.com/highcharts/xAxis.labels.style) like so in my JS literal options file:
```
xAxis: {
  labels: {
    style: {
      color: "red",
    }
  }
}
```

The outputted JavaScript is:
```
xAxis: {
  labels: {
    style: "{\\'color\\': \\'red\\'}"
  }
}
```

This doesn't happen when setting something else, like [title.style](https://api.highcharts.com/highcharts/title.style).

**Comment by hcpchris** [comment]
Hmmm - that's odd, because they should be using a similar (if not identical) class for their style options. I'll take a closer look to see why it's serializing differently.

**Comment by hcpchris** [comment]
@ndrwkim : Thanks for this - another good catch. I found the inconsistency and patched it in v.1.3.1 which was just released (and so the issue auto-closed).

**Comment by ndrwkim** [comment]
This works now. Thank you for the quick fixes!
