### ISSUE TITLE
legend.itemStyle isn't applying styles correctly

### ISSUE THREAD

**Issue by ndrwkim** [highcharts-for-python/highcharts-core#93]
[legend.itemStyle](https://api.highcharts.com/highcharts/legend.itemStyle) doesn't seem to be accepting a `Highcharts.CSSObject`. When trying to apply:
```
legend: {
  itemStyle: {
    color: "#5f5e5e",
    fontFamily: "Roboto",
    fontSize: "12px"
  }
},
```
I get this error:
`value ({'color': '#5f5e5e', 'fontFamily': 'Roboto', 'fontSize': '12px'}) was not coerced to a string`

**Comment by hcpchris** [comment]
Thanks, @ndrwkim : This looks to be a bug. I'll patch it in the next patch release (v.1.3.5, likely to be released on Tuesday, August 15).

**Comment by hcpchris** [comment]
Hi @ndrwkim : Fixed the bug in validating ``Legend`` style-related properties. The issue was auto-closed, but the fix should be available in v.1.3.5 which was just released. Hopefully this works for you, and if not, please let me know!
