### ISSUE TITLE
navigation.menuItemStyle doesn't seem to work

### ISSUE THREAD

**Issue by ndrwkim** [highcharts-for-python/highcharts-core#95]
[navigation.menuItemStyle](https://api.highcharts.com/highcharts/navigation.menuItemStyle) doesn't seem to work. When trying to apply:
```
navigation: {
    menuItemStyle: {
        color: "#5f5e5e",
        fontFamily: "Roboto",
        fontSize: "12px",
        fontWeight: "400"
    }
}
```
via a shared options JS literal, the JS output doesn't include the `navigation` object key.

**Comment by hcpchris** [comment]
Thanks, @ndrwkim : A fix for this bug has been included in v.1.3.6 which was just released. Thanks for bringing it to my attention!
