### ISSUE TITLE
Can't create zoomable charts.

### ISSUE THREAD

**Issue by abbas-mohd56** [highcharts-for-python/highcharts-core#97]
**Can't create zoomable charts.**

I have a `shared_options.js` file with the following options defined
```javascript
{
  chart: {
    zoomType: "x",
  },
  tooltip: {
    shared: true
  },
  xAxis: {
    type: "datetime",
  },
}
```
Creating any options instance seems to omit the `zoomType` option of `chart`. For example, if I do
```python
from highcharts_core.highcharts import  SharedOptions
options = SharedOptions.from_js_literal("shared_options.js")
print(options.to_js_literal)
```
This generates the following options
```javascript
Highcharts.setOptions({
  tooltip: {
  shared: true
},
  xAxis: {
  type: 'datetime'
}
});
```
From what I found the `ChartOption` class is missing the `zoom_type` property. I tried configuring the chart with `zooming` property but the charts still didn't zoom because from what I understand, the zooming property is ineffective if `zoomType` is not defined.

**Environment:**
 - OS: Linux
 - Python Version: 3.10.8
 - Highcharts Python Version: 1.3.6

**Comment by hcpchris** [comment]
So the reason why `zoomType` is not implemented in Highcharts for Python is that per the Highcharts (JS) documentation the `zoomType` property is deprecated (see [here](https://api.highcharts.com/highcharts/chart.zoomType) ). However, you should be able to enable zooming by configuring it in the `zooming` property as below:

```
chart: {
  zooming: {
    type: 'xy'
  }
}
```

in your shared options, and that should enable zooming for you. Testing it seems to work (see [here](https://jsfiddle.net/highchartspython/L5tm1rno/8/) ). Note that if all you set is the `zooming.type` property, then to actually zoom in on the chart you need to click on the chart and drag the section that you want to zoom into. If you want different zooming behavior, the `zooming` property contains other options you can set to fine-tune the zooming behavior.

**Comment by hcpchris** [comment]
For the moment, I'll close this issue since hopefully the above helps you achieve the effect you're looking for. If for some reason it's still not working for you, can you re-open and share the full output of your shared options and one of your sample charts? (you can strip some of the data out or provide dummy data in the series if you'd like)? It's possible there's something else going on that is preventing zooming from functioning as expected when enabled through shared options.

**Comment by abbas-mohd56** [comment]
Thank you for your input @hcpchris, So the reason why it wasn't working for me was because I was using an older version of Highcharts JS (v9.3.3). After upgrading my Highcharts JS version to the latest version (v11.1.0), configuring charts with the `zooming` property enabled zooming. Thanks again!
