### ISSUE TITLE
`copy()` method raises an error when creating options instance from `from_js_literal()`

### ISSUE THREAD

**Issue by abbas-mohd56** [highcharts-for-python/highcharts-core#98]
**`copy()` method raises an error**
When creating an `HighchartsOptions` instance using `from_js_literal()`, Using the `copy()` method of the instance raises an Error

**To Reproduce**
Create a `shared_options.js` file with the following options defined
```javascript
{
  chart: {
    zoomType: "x",
  },
  tooltip: {
    shared: true
  },
  xAxis: {
    type: "datetime",
  },
}
```
Running the following python code raises an error
```python
from highcharts_core.highcharts import HighchartsOptions

shared_options = HighchartsOptions.from_js_literal("shared_options.js")
chart_A_options = shared_options.copy()
```

**Environment:**
 - OS: Linux
 - Python Version:3.10.8
 - Highcharts Python Version: 1.3.6

**Comment by hcpchris** [comment]
Thanks, @abbas-mohd56 - this definitely look to be a bug. I'll patch it later today and release v.1.3.7 with a fix.

**Comment by hcpchris** [comment]
Hi @abbas-mohd56 : Just confirming that this bug was fixed in the patch release for v.1.3.7. If you upgrade to that latest version using ``pip install --upgrade highcharts-core``, this bug should be resolved. If it re-occurs, feel free to re-open this issue.
